apiVersion: v1
kind: Pod
metadata:
  name: triton-client-v100-bert
  namespace: default
  labels:
    name: triton-client-v100-bert
spec:
  containers:
  - name: triton-client
    image: gshaibi/triton-client
    command:
    - "perf_analyzer"
    - "-m"
    - "bert"
    - "--request-rate-range"
    - "30"
    - "-p"
    - "3600000"
    - "-u"
    - "triton-server-v100-bert1-00001-private.runai-project-a"
    - "--input-data"
    - "/profiling_data"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
